LARGURA_PADRAO = 1366
ALTURA_PADRAO = 768

estados = {
    "menu_inicial": 1,
    "login": 2,
    "cadastro": 3,
    "menu_logado": 4,
    "buscar_sala": 5,
    "partida_local": 6,
    "historico": 7,
    "desconectar": 8,
    "em_saguao": 9,
    "sair": 20
}

cores = {
    "azul":"blue",
    "amarelo":"yellow",
    "branco":"white",
    "preto":"black",
    "verde":"green",
    "vermelho":"red"
}

API_KEY = 'AIzaSyC-YLbsPI1jh9iTTn0oowvoJRx0i7mcVmY'

dicionario_territorios = {
    1:"Congo",
    2:"Sudao",
    3:"Egito",
    4:"Madagascar",
    5:"Argelia",
    6:"Africa do Sul",
    7:"Alaska",
    8:"Alberta",
    9:"Mexico",
    10:"Nova Iorque",
    11:"Groenlandia",
    12:"Mackenzie",
    13:"Ottawa",
    14:"Labrador",
    15:"California",
    16:"Argentina",
    17:"Brasil",
    18:"Peru",
    19:"Venezuela",
    20:"Aral",
    21:"China",
    22:"India",
    23:"Tchita",
    24:"Japao",
    25:"Vladivostok",
    26:"Oriente Medio",
    27:"Mongolia",
    28:"Vietna",
    29:"Dudinka",
    30:"Omsk",
    31:"Siberia",
    32:"Reino Unido",
    33:"Islandia",
    34:"Alemanha",
    35:"Escandinavia",
    36:"Italia",
    37:"Moscou",
    38:"Franca",
    39:"Australia Oriental",
    40:"Sumatra",
    41:"Nova Guine",
    42:"Australia Ocidental"
}

dicionario_figura_territorio = {
    1:"Triangulo",
    2:"Quadrado",
    3:"Circulo",
    4:"Triangulo",
    5:"Quadrado",
    6:"Circulo",
    7:"Triangulo",
    8:"Quadrado",
    9:"Circulo",
    10:"Triangulo",
    11:"Quadrado",
    12:"Circulo",
    13:"Triangulo",
    14:"Quadrado",
    15:"Circulo",
    16:"Triangulo",
    17:"Quadrado",
    18:"Circulo",
    19:"Triangulo",
    20:"Quadrado",
    21:"Circulo",
    22:"Triangulo",
    23:"Quadrado",
    24:"Circulo",
    25:"Triangulo",
    26:"Quadrado",
    27:"Circulo",
    28:"Triangulo",
    29:"Quadrado",
    30:"Circulo",
    31:"Triangulo",
    32:"Quadrado",
    33:"Circulo",
    34:"Triangulo",
    35:"Quadrado",
    36:"Circulo",
    37:"Triangulo",
    38:"Quadrado",
    39:"Circulo",
    40:"Triangulo",
    41:"Quadrado",
    42:"Circulo"
}